interface RegisterInfo {
  name: string;
  addr: number;
  readable: boolean;
  writable: boolean;
  selfReset: boolean;
}

export const REGISTERS: Record<number, RegisterInfo> = {
  0x00: {
    name: "MCU_RESET",
    addr: 0x00,
    readable: false,
    writable: true,
    selfReset: true,
  },
  0x01: {
    name: "HOST_XFER_CTRL",
    addr: 0x01,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0x19: {
    name: "SPI_RTY",
    addr: 0x19,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0xb1: {
    name: "FRAME_MODE",
    addr: 0xb1,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0xb2: {
    name: "FW_VERSION_1",
    addr: 0xb2,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xb3: {
    name: "FW_VERSION_2",
    addr: 0xb3,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xb4: {
    name: "FRAME_RATE",
    addr: 0xb4,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xb5: {
    name: "SLEEP_MODE",
    addr: 0xb5,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0xb6: {
    name: "STATUS",
    addr: 0xb6,
    readable: true,
    writable: false,
    selfReset: true,
  },
  0xb7: {
    name: "CLK_SPEED",
    addr: 0xb7,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xb9: {
    name: "SENXOR_GAIN",
    addr: 0xb9,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xba: {
    name: "SENXOR_TYPE",
    addr: 0xba,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xbb: {
    name: "MODULE_TYPE",
    addr: 0xbb,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0x33: {
    name: "MCU_TYPE",
    addr: 0x33,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xbc: {
    name: "TEMP_CONVERT_CTRL",
    addr: 0xbc,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xc2: {
    name: "SENSITIVITY_FACTOR",
    addr: 0xc2,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xc5: {
    name: "SELF_CALIBRATION",
    addr: 0xc5,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0xca: {
    name: "EMISSIVITY",
    addr: 0xca,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xcb: {
    name: "OFFSET_CORR",
    addr: 0xcb,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xcd: {
    name: "OBJECT_TEMP_FACTOR",
    addr: 0xcd,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xe0: {
    name: "SENXOR_ID_0",
    addr: 0xe0,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe1: {
    name: "SENXOR_ID_1",
    addr: 0xe1,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe2: {
    name: "SENXOR_ID_2",
    addr: 0xe2,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe3: {
    name: "SENXOR_ID_3",
    addr: 0xe3,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe4: {
    name: "SENXOR_ID_4",
    addr: 0xe4,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe5: {
    name: "SENXOR_ID_5",
    addr: 0xe5,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xe6: {
    name: "SENXOR_ID_6",
    addr: 0xe6,
    readable: true,
    writable: false,
    selfReset: false,
  },
  0xd8: {
    name: "USER_FLASH_CTRL",
    addr: 0xd8,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x31: {
    name: "FRAME_FORMAT",
    addr: 0x31,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x20: {
    name: "STARK_CTRL",
    addr: 0x20,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x21: {
    name: "STARK_CUTOFF",
    addr: 0x21,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x22: {
    name: "STARK_GRAD",
    addr: 0x22,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x23: {
    name: "STARK_SCALE",
    addr: 0x23,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x25: {
    name: "MMS_CTRL",
    addr: 0x25,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0x30: {
    name: "MEDIAN_CTRL",
    addr: 0x30,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xd0: {
    name: "FILTER_CONTROL",
    addr: 0xd0,
    readable: true,
    writable: true,
    selfReset: true,
  },
  0xd1: {
    name: "FILTER_SETTING_1_0",
    addr: 0xd1,
    readable: true,
    writable: true,
    selfReset: false,
  },
  0xd2: {
    name: "FILTER_SETTING_1_1",
    addr: 0xd2,
    readable: true,
    writable: true,
    selfReset: false,
  },
};
